site_name: Security Spectrum
site_url: https://docs.securityspectrum.io

# Repository
repo_name: squidfunk/mkdocs-material
repo_url: https://github.com/squidfunk/mkdocs-material

nav:
    - Home: index.md
    - Quickstart: quickstart.md
    - End-to-End Encryption (E2EE): e2ee.md
    - Limitations: limitations.md
    - About: about.md
theme:
  features:
    - navigation.instant
  font:
    text: Roboto
    code: Roboto Mono
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true